---
deployment:
  tasks:
    - export DEPLOYPATH=/home/koepinan/admin.koepinang.com
    - export REPOPATH=/home/koepinan/ci4_shop
    #- /usr/bin/rsync -Paz * $DEPLOYPATH --delete

    - /usr/bin/rsync -Paz public/* $DEPLOYPATH --delete
    - /usr/bin/rsync -Paz * $REPOPATH --delete
