---
deployment:
  tasks:
    - export DEPLOYPATH=/home/waysinwe/public_html
    - export REPOPATH=/home/waysinwe/ci4_shop
    #- /usr/bin/rsync -Paz * $DEPLOYPATH --delete

    - /usr/bin/rsync -Paz public/* $DEPLOYPATH --delete
    - /usr/bin/rsync -Paz * $REPOPATH --delete
