---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sablonk4/admin.ruangdaring.my.id
    - export REPOPATH=/home/sablonk4/ci4_shop
    #- /usr/bin/rsync -Paz * $DEPLOYPATH --delete

    - /usr/bin/rsync -Paz public/* $DEPLOYPATH --delete
    - /usr/bin/rsync -Paz * $REPOPATH --delete
